/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as TestFloatingRouteImport } from './routes/test.floating'
import { Route as ManageStudentRouteImport } from './routes/manage.student'
import { Route as ManageResumeRouteImport } from './routes/manage.resume'
import { Route as ManageDeleteRouteImport } from './routes/manage.delete'
import { Route as BookWriteRouteImport } from './routes/book.write'
import { Route as SidebarReviewRouteImport } from './routes/_sidebar._review'
import { Route as SidebarProgressRouteImport } from './routes/_sidebar._progress'
import { Route as OauthKakaoCallbackRouteImport } from './routes/oauth.kakao.callback'
import { Route as SidebarProgressProgressIndexRouteImport } from './routes/_sidebar._progress.progress.index'
import { Route as SidebarReviewReviewCheckIndexRouteImport } from './routes/_sidebar._review.review.check.index'
import { Route as SidebarReviewReviewAssignmentIndexRouteImport } from './routes/_sidebar._review.review.assignment.index'
import { Route as SidebarReviewReviewAssignmentCreateIndexRouteImport } from './routes/_sidebar._review.review.assignment.create.index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFloatingRoute = TestFloatingRouteImport.update({
  id: '/test/floating',
  path: '/test/floating',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStudentRoute = ManageStudentRouteImport.update({
  id: '/manage/student',
  path: '/manage/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageResumeRoute = ManageResumeRouteImport.update({
  id: '/manage/resume',
  path: '/manage/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDeleteRoute = ManageDeleteRouteImport.update({
  id: '/manage/delete',
  path: '/manage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const BookWriteRoute = BookWriteRouteImport.update({
  id: '/book/write',
  path: '/book/write',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarReviewRoute = SidebarReviewRouteImport.update({
  id: '/_review',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarProgressRoute = SidebarProgressRouteImport.update({
  id: '/_progress',
  getParentRoute: () => SidebarRoute,
} as any)
const OauthKakaoCallbackRoute = OauthKakaoCallbackRouteImport.update({
  id: '/oauth/kakao/callback',
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProgressProgressIndexRoute =
  SidebarProgressProgressIndexRouteImport.update({
    id: '/progress/',
    path: '/progress/',
    getParentRoute: () => SidebarProgressRoute,
  } as any)
const SidebarReviewReviewCheckIndexRoute =
  SidebarReviewReviewCheckIndexRouteImport.update({
    id: '/review/check/',
    path: '/review/check/',
    getParentRoute: () => SidebarReviewRoute,
  } as any)
const SidebarReviewReviewAssignmentIndexRoute =
  SidebarReviewReviewAssignmentIndexRouteImport.update({
    id: '/review/assignment/',
    path: '/review/assignment/',
    getParentRoute: () => SidebarReviewRoute,
  } as any)
const SidebarReviewReviewAssignmentCreateIndexRoute =
  SidebarReviewReviewAssignmentCreateIndexRouteImport.update({
    id: '/review/assignment/create/',
    path: '/review/assignment/create/',
    getParentRoute: () => SidebarReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/progress/': typeof SidebarProgressProgressIndexRoute
  '/review/assignment/': typeof SidebarReviewReviewAssignmentIndexRoute
  '/review/check/': typeof SidebarReviewReviewCheckIndexRoute
  '/review/assignment/create/': typeof SidebarReviewReviewAssignmentCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/progress': typeof SidebarProgressProgressIndexRoute
  '/review/assignment': typeof SidebarReviewReviewAssignmentIndexRoute
  '/review/check': typeof SidebarReviewReviewCheckIndexRoute
  '/review/assignment/create': typeof SidebarReviewReviewAssignmentCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_sidebar/_progress': typeof SidebarProgressRouteWithChildren
  '/_sidebar/_review': typeof SidebarReviewRouteWithChildren
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/_sidebar/_progress/progress/': typeof SidebarProgressProgressIndexRoute
  '/_sidebar/_review/review/assignment/': typeof SidebarReviewReviewAssignmentIndexRoute
  '/_sidebar/_review/review/check/': typeof SidebarReviewReviewCheckIndexRoute
  '/_sidebar/_review/review/assignment/create/': typeof SidebarReviewReviewAssignmentCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/oauth/kakao/callback'
    | '/progress/'
    | '/review/assignment/'
    | '/review/check/'
    | '/review/assignment/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book'
    | '/oauth/kakao/callback'
    | '/progress'
    | '/review/assignment'
    | '/review/check'
    | '/review/assignment/create'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/login'
    | '/profile'
    | '/_sidebar/_progress'
    | '/_sidebar/_review'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/oauth/kakao/callback'
    | '/_sidebar/_progress/progress/'
    | '/_sidebar/_review/review/assignment/'
    | '/_sidebar/_review/review/check/'
    | '/_sidebar/_review/review/assignment/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  BookWriteRoute: typeof BookWriteRoute
  ManageDeleteRoute: typeof ManageDeleteRoute
  ManageResumeRoute: typeof ManageResumeRoute
  ManageStudentRoute: typeof ManageStudentRoute
  TestFloatingRoute: typeof TestFloatingRoute
  BookIndexRoute: typeof BookIndexRoute
  OauthKakaoCallbackRoute: typeof OauthKakaoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/floating': {
      id: '/test/floating'
      path: '/test/floating'
      fullPath: '/test/floating'
      preLoaderRoute: typeof TestFloatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/student': {
      id: '/manage/student'
      path: '/manage/student'
      fullPath: '/manage/student'
      preLoaderRoute: typeof ManageStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/resume': {
      id: '/manage/resume'
      path: '/manage/resume'
      fullPath: '/manage/resume'
      preLoaderRoute: typeof ManageResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/delete': {
      id: '/manage/delete'
      path: '/manage/delete'
      fullPath: '/manage/delete'
      preLoaderRoute: typeof ManageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/write': {
      id: '/book/write'
      path: '/book/write'
      fullPath: '/book/write'
      preLoaderRoute: typeof BookWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_review': {
      id: '/_sidebar/_review'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarReviewRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/_progress': {
      id: '/_sidebar/_progress'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarProgressRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/oauth/kakao/callback': {
      id: '/oauth/kakao/callback'
      path: '/oauth/kakao/callback'
      fullPath: '/oauth/kakao/callback'
      preLoaderRoute: typeof OauthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_progress/progress/': {
      id: '/_sidebar/_progress/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof SidebarProgressProgressIndexRouteImport
      parentRoute: typeof SidebarProgressRoute
    }
    '/_sidebar/_review/review/check/': {
      id: '/_sidebar/_review/review/check/'
      path: '/review/check'
      fullPath: '/review/check/'
      preLoaderRoute: typeof SidebarReviewReviewCheckIndexRouteImport
      parentRoute: typeof SidebarReviewRoute
    }
    '/_sidebar/_review/review/assignment/': {
      id: '/_sidebar/_review/review/assignment/'
      path: '/review/assignment'
      fullPath: '/review/assignment/'
      preLoaderRoute: typeof SidebarReviewReviewAssignmentIndexRouteImport
      parentRoute: typeof SidebarReviewRoute
    }
    '/_sidebar/_review/review/assignment/create/': {
      id: '/_sidebar/_review/review/assignment/create/'
      path: '/review/assignment/create'
      fullPath: '/review/assignment/create/'
      preLoaderRoute: typeof SidebarReviewReviewAssignmentCreateIndexRouteImport
      parentRoute: typeof SidebarReviewRoute
    }
  }
}

interface SidebarProgressRouteChildren {
  SidebarProgressProgressIndexRoute: typeof SidebarProgressProgressIndexRoute
}

const SidebarProgressRouteChildren: SidebarProgressRouteChildren = {
  SidebarProgressProgressIndexRoute: SidebarProgressProgressIndexRoute,
}

const SidebarProgressRouteWithChildren = SidebarProgressRoute._addFileChildren(
  SidebarProgressRouteChildren,
)

interface SidebarReviewRouteChildren {
  SidebarReviewReviewAssignmentIndexRoute: typeof SidebarReviewReviewAssignmentIndexRoute
  SidebarReviewReviewCheckIndexRoute: typeof SidebarReviewReviewCheckIndexRoute
  SidebarReviewReviewAssignmentCreateIndexRoute: typeof SidebarReviewReviewAssignmentCreateIndexRoute
}

const SidebarReviewRouteChildren: SidebarReviewRouteChildren = {
  SidebarReviewReviewAssignmentIndexRoute:
    SidebarReviewReviewAssignmentIndexRoute,
  SidebarReviewReviewCheckIndexRoute: SidebarReviewReviewCheckIndexRoute,
  SidebarReviewReviewAssignmentCreateIndexRoute:
    SidebarReviewReviewAssignmentCreateIndexRoute,
}

const SidebarReviewRouteWithChildren = SidebarReviewRoute._addFileChildren(
  SidebarReviewRouteChildren,
)

interface SidebarRouteChildren {
  SidebarProgressRoute: typeof SidebarProgressRouteWithChildren
  SidebarReviewRoute: typeof SidebarReviewRouteWithChildren
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarProgressRoute: SidebarProgressRouteWithChildren,
  SidebarReviewRoute: SidebarReviewRouteWithChildren,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  BookWriteRoute: BookWriteRoute,
  ManageDeleteRoute: ManageDeleteRoute,
  ManageResumeRoute: ManageResumeRoute,
  ManageStudentRoute: ManageStudentRoute,
  TestFloatingRoute: TestFloatingRoute,
  BookIndexRoute: BookIndexRoute,
  OauthKakaoCallbackRoute: OauthKakaoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
