/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as TestFloatingRouteImport } from './routes/test.floating'
import { Route as ManageStudentRouteImport } from './routes/manage.student'
import { Route as ManageResumeRouteImport } from './routes/manage.resume'
import { Route as ManageDeleteRouteImport } from './routes/manage.delete'
import { Route as BookWriteRouteImport } from './routes/book.write'
import { Route as SidebarAssignedRouteImport } from './routes/_sidebar._assigned'
import { Route as OauthKakaoCallbackRouteImport } from './routes/oauth.kakao.callback'
import { Route as SidebarAssignedProgressRouteImport } from './routes/_sidebar._assigned._progress'
import { Route as SidebarAssignedCheckRouteImport } from './routes/_sidebar._assigned._check'
import { Route as SidebarAssignedAssignmentRouteImport } from './routes/_sidebar._assigned._assignment'
import { Route as SidebarAssignedProgressProgressIndexRouteImport } from './routes/_sidebar._assigned._progress.progress.index'
import { Route as SidebarAssignedCheckCheckIndexRouteImport } from './routes/_sidebar._assigned._check.check.index'
import { Route as SidebarAssignedAssignmentAssignmentIndexRouteImport } from './routes/_sidebar._assigned._assignment.assignment.index'
import { Route as SidebarAssignedAssignmentAssignmentCreateIndexRouteImport } from './routes/_sidebar._assigned._assignment.assignment.create.index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFloatingRoute = TestFloatingRouteImport.update({
  id: '/test/floating',
  path: '/test/floating',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStudentRoute = ManageStudentRouteImport.update({
  id: '/manage/student',
  path: '/manage/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageResumeRoute = ManageResumeRouteImport.update({
  id: '/manage/resume',
  path: '/manage/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDeleteRoute = ManageDeleteRouteImport.update({
  id: '/manage/delete',
  path: '/manage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const BookWriteRoute = BookWriteRouteImport.update({
  id: '/book/write',
  path: '/book/write',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarAssignedRoute = SidebarAssignedRouteImport.update({
  id: '/_assigned',
  getParentRoute: () => SidebarRoute,
} as any)
const OauthKakaoCallbackRoute = OauthKakaoCallbackRouteImport.update({
  id: '/oauth/kakao/callback',
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarAssignedProgressRoute = SidebarAssignedProgressRouteImport.update({
  id: '/_progress',
  getParentRoute: () => SidebarAssignedRoute,
} as any)
const SidebarAssignedCheckRoute = SidebarAssignedCheckRouteImport.update({
  id: '/_check',
  getParentRoute: () => SidebarAssignedRoute,
} as any)
const SidebarAssignedAssignmentRoute =
  SidebarAssignedAssignmentRouteImport.update({
    id: '/_assignment',
    getParentRoute: () => SidebarAssignedRoute,
  } as any)
const SidebarAssignedProgressProgressIndexRoute =
  SidebarAssignedProgressProgressIndexRouteImport.update({
    id: '/progress/',
    path: '/progress/',
    getParentRoute: () => SidebarAssignedProgressRoute,
  } as any)
const SidebarAssignedCheckCheckIndexRoute =
  SidebarAssignedCheckCheckIndexRouteImport.update({
    id: '/check/',
    path: '/check/',
    getParentRoute: () => SidebarAssignedCheckRoute,
  } as any)
const SidebarAssignedAssignmentAssignmentIndexRoute =
  SidebarAssignedAssignmentAssignmentIndexRouteImport.update({
    id: '/assignment/',
    path: '/assignment/',
    getParentRoute: () => SidebarAssignedAssignmentRoute,
  } as any)
const SidebarAssignedAssignmentAssignmentCreateIndexRoute =
  SidebarAssignedAssignmentAssignmentCreateIndexRouteImport.update({
    id: '/assignment/create/',
    path: '/assignment/create/',
    getParentRoute: () => SidebarAssignedAssignmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/assignment/': typeof SidebarAssignedAssignmentAssignmentIndexRoute
  '/check/': typeof SidebarAssignedCheckCheckIndexRoute
  '/progress/': typeof SidebarAssignedProgressProgressIndexRoute
  '/assignment/create/': typeof SidebarAssignedAssignmentAssignmentCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/assignment': typeof SidebarAssignedAssignmentAssignmentIndexRoute
  '/check': typeof SidebarAssignedCheckCheckIndexRoute
  '/progress': typeof SidebarAssignedProgressProgressIndexRoute
  '/assignment/create': typeof SidebarAssignedAssignmentAssignmentCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_sidebar/_assigned': typeof SidebarAssignedRouteWithChildren
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/_sidebar/_assigned/_assignment': typeof SidebarAssignedAssignmentRouteWithChildren
  '/_sidebar/_assigned/_check': typeof SidebarAssignedCheckRouteWithChildren
  '/_sidebar/_assigned/_progress': typeof SidebarAssignedProgressRouteWithChildren
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/_sidebar/_assigned/_assignment/assignment/': typeof SidebarAssignedAssignmentAssignmentIndexRoute
  '/_sidebar/_assigned/_check/check/': typeof SidebarAssignedCheckCheckIndexRoute
  '/_sidebar/_assigned/_progress/progress/': typeof SidebarAssignedProgressProgressIndexRoute
  '/_sidebar/_assigned/_assignment/assignment/create/': typeof SidebarAssignedAssignmentAssignmentCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/oauth/kakao/callback'
    | '/assignment/'
    | '/check/'
    | '/progress/'
    | '/assignment/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book'
    | '/oauth/kakao/callback'
    | '/assignment'
    | '/check'
    | '/progress'
    | '/assignment/create'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/login'
    | '/profile'
    | '/_sidebar/_assigned'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/_sidebar/_assigned/_assignment'
    | '/_sidebar/_assigned/_check'
    | '/_sidebar/_assigned/_progress'
    | '/oauth/kakao/callback'
    | '/_sidebar/_assigned/_assignment/assignment/'
    | '/_sidebar/_assigned/_check/check/'
    | '/_sidebar/_assigned/_progress/progress/'
    | '/_sidebar/_assigned/_assignment/assignment/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  BookWriteRoute: typeof BookWriteRoute
  ManageDeleteRoute: typeof ManageDeleteRoute
  ManageResumeRoute: typeof ManageResumeRoute
  ManageStudentRoute: typeof ManageStudentRoute
  TestFloatingRoute: typeof TestFloatingRoute
  BookIndexRoute: typeof BookIndexRoute
  OauthKakaoCallbackRoute: typeof OauthKakaoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/floating': {
      id: '/test/floating'
      path: '/test/floating'
      fullPath: '/test/floating'
      preLoaderRoute: typeof TestFloatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/student': {
      id: '/manage/student'
      path: '/manage/student'
      fullPath: '/manage/student'
      preLoaderRoute: typeof ManageStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/resume': {
      id: '/manage/resume'
      path: '/manage/resume'
      fullPath: '/manage/resume'
      preLoaderRoute: typeof ManageResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/delete': {
      id: '/manage/delete'
      path: '/manage/delete'
      fullPath: '/manage/delete'
      preLoaderRoute: typeof ManageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/write': {
      id: '/book/write'
      path: '/book/write'
      fullPath: '/book/write'
      preLoaderRoute: typeof BookWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_assigned': {
      id: '/_sidebar/_assigned'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarAssignedRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/oauth/kakao/callback': {
      id: '/oauth/kakao/callback'
      path: '/oauth/kakao/callback'
      fullPath: '/oauth/kakao/callback'
      preLoaderRoute: typeof OauthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_assigned/_progress': {
      id: '/_sidebar/_assigned/_progress'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarAssignedProgressRouteImport
      parentRoute: typeof SidebarAssignedRoute
    }
    '/_sidebar/_assigned/_check': {
      id: '/_sidebar/_assigned/_check'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarAssignedCheckRouteImport
      parentRoute: typeof SidebarAssignedRoute
    }
    '/_sidebar/_assigned/_assignment': {
      id: '/_sidebar/_assigned/_assignment'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarAssignedAssignmentRouteImport
      parentRoute: typeof SidebarAssignedRoute
    }
    '/_sidebar/_assigned/_progress/progress/': {
      id: '/_sidebar/_assigned/_progress/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof SidebarAssignedProgressProgressIndexRouteImport
      parentRoute: typeof SidebarAssignedProgressRoute
    }
    '/_sidebar/_assigned/_check/check/': {
      id: '/_sidebar/_assigned/_check/check/'
      path: '/check'
      fullPath: '/check/'
      preLoaderRoute: typeof SidebarAssignedCheckCheckIndexRouteImport
      parentRoute: typeof SidebarAssignedCheckRoute
    }
    '/_sidebar/_assigned/_assignment/assignment/': {
      id: '/_sidebar/_assigned/_assignment/assignment/'
      path: '/assignment'
      fullPath: '/assignment/'
      preLoaderRoute: typeof SidebarAssignedAssignmentAssignmentIndexRouteImport
      parentRoute: typeof SidebarAssignedAssignmentRoute
    }
    '/_sidebar/_assigned/_assignment/assignment/create/': {
      id: '/_sidebar/_assigned/_assignment/assignment/create/'
      path: '/assignment/create'
      fullPath: '/assignment/create/'
      preLoaderRoute: typeof SidebarAssignedAssignmentAssignmentCreateIndexRouteImport
      parentRoute: typeof SidebarAssignedAssignmentRoute
    }
  }
}

interface SidebarAssignedAssignmentRouteChildren {
  SidebarAssignedAssignmentAssignmentIndexRoute: typeof SidebarAssignedAssignmentAssignmentIndexRoute
  SidebarAssignedAssignmentAssignmentCreateIndexRoute: typeof SidebarAssignedAssignmentAssignmentCreateIndexRoute
}

const SidebarAssignedAssignmentRouteChildren: SidebarAssignedAssignmentRouteChildren =
  {
    SidebarAssignedAssignmentAssignmentIndexRoute:
      SidebarAssignedAssignmentAssignmentIndexRoute,
    SidebarAssignedAssignmentAssignmentCreateIndexRoute:
      SidebarAssignedAssignmentAssignmentCreateIndexRoute,
  }

const SidebarAssignedAssignmentRouteWithChildren =
  SidebarAssignedAssignmentRoute._addFileChildren(
    SidebarAssignedAssignmentRouteChildren,
  )

interface SidebarAssignedCheckRouteChildren {
  SidebarAssignedCheckCheckIndexRoute: typeof SidebarAssignedCheckCheckIndexRoute
}

const SidebarAssignedCheckRouteChildren: SidebarAssignedCheckRouteChildren = {
  SidebarAssignedCheckCheckIndexRoute: SidebarAssignedCheckCheckIndexRoute,
}

const SidebarAssignedCheckRouteWithChildren =
  SidebarAssignedCheckRoute._addFileChildren(SidebarAssignedCheckRouteChildren)

interface SidebarAssignedProgressRouteChildren {
  SidebarAssignedProgressProgressIndexRoute: typeof SidebarAssignedProgressProgressIndexRoute
}

const SidebarAssignedProgressRouteChildren: SidebarAssignedProgressRouteChildren =
  {
    SidebarAssignedProgressProgressIndexRoute:
      SidebarAssignedProgressProgressIndexRoute,
  }

const SidebarAssignedProgressRouteWithChildren =
  SidebarAssignedProgressRoute._addFileChildren(
    SidebarAssignedProgressRouteChildren,
  )

interface SidebarAssignedRouteChildren {
  SidebarAssignedAssignmentRoute: typeof SidebarAssignedAssignmentRouteWithChildren
  SidebarAssignedCheckRoute: typeof SidebarAssignedCheckRouteWithChildren
  SidebarAssignedProgressRoute: typeof SidebarAssignedProgressRouteWithChildren
}

const SidebarAssignedRouteChildren: SidebarAssignedRouteChildren = {
  SidebarAssignedAssignmentRoute: SidebarAssignedAssignmentRouteWithChildren,
  SidebarAssignedCheckRoute: SidebarAssignedCheckRouteWithChildren,
  SidebarAssignedProgressRoute: SidebarAssignedProgressRouteWithChildren,
}

const SidebarAssignedRouteWithChildren = SidebarAssignedRoute._addFileChildren(
  SidebarAssignedRouteChildren,
)

interface SidebarRouteChildren {
  SidebarAssignedRoute: typeof SidebarAssignedRouteWithChildren
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarAssignedRoute: SidebarAssignedRouteWithChildren,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  BookWriteRoute: BookWriteRoute,
  ManageDeleteRoute: ManageDeleteRoute,
  ManageResumeRoute: ManageResumeRoute,
  ManageStudentRoute: ManageStudentRoute,
  TestFloatingRoute: TestFloatingRoute,
  BookIndexRoute: BookIndexRoute,
  OauthKakaoCallbackRoute: OauthKakaoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
