/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as TestFloatingRouteImport } from './routes/test.floating'
import { Route as ManageStudentRouteImport } from './routes/manage.student'
import { Route as ManageResumeRouteImport } from './routes/manage.resume'
import { Route as ManageDeleteRouteImport } from './routes/manage.delete'
import { Route as BookWriteRouteImport } from './routes/book.write'
import { Route as SidebarReviewCheckRouteImport } from './routes/_sidebar._review-check'
import { Route as SidebarProgressRouteImport } from './routes/_sidebar._progress'
import { Route as OauthKakaoCallbackRouteImport } from './routes/oauth.kakao.callback'
import { Route as SidebarReviewCheckReviewCheckIndexRouteImport } from './routes/_sidebar._review-check.review-check.index'
import { Route as SidebarProgressProgressIndexRouteImport } from './routes/_sidebar._progress.progress.index'
import { Route as SidebarReviewCheckReviewCheckSyllabusRouteImport } from './routes/_sidebar._review-check.review-check.syllabus'
import { Route as SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRouteImport } from './routes/_sidebar._review-check.review-check.syllabus.$syllabus_id.index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFloatingRoute = TestFloatingRouteImport.update({
  id: '/test/floating',
  path: '/test/floating',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStudentRoute = ManageStudentRouteImport.update({
  id: '/manage/student',
  path: '/manage/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageResumeRoute = ManageResumeRouteImport.update({
  id: '/manage/resume',
  path: '/manage/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDeleteRoute = ManageDeleteRouteImport.update({
  id: '/manage/delete',
  path: '/manage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const BookWriteRoute = BookWriteRouteImport.update({
  id: '/book/write',
  path: '/book/write',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarReviewCheckRoute = SidebarReviewCheckRouteImport.update({
  id: '/_review-check',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarProgressRoute = SidebarProgressRouteImport.update({
  id: '/_progress',
  getParentRoute: () => SidebarRoute,
} as any)
const OauthKakaoCallbackRoute = OauthKakaoCallbackRouteImport.update({
  id: '/oauth/kakao/callback',
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarReviewCheckReviewCheckIndexRoute =
  SidebarReviewCheckReviewCheckIndexRouteImport.update({
    id: '/review-check/',
    path: '/review-check/',
    getParentRoute: () => SidebarReviewCheckRoute,
  } as any)
const SidebarProgressProgressIndexRoute =
  SidebarProgressProgressIndexRouteImport.update({
    id: '/progress/',
    path: '/progress/',
    getParentRoute: () => SidebarProgressRoute,
  } as any)
const SidebarReviewCheckReviewCheckSyllabusRoute =
  SidebarReviewCheckReviewCheckSyllabusRouteImport.update({
    id: '/review-check/syllabus',
    path: '/review-check/syllabus',
    getParentRoute: () => SidebarReviewCheckRoute,
  } as any)
const SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute =
  SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRouteImport.update({
    id: '/$syllabus_id/',
    path: '/$syllabus_id/',
    getParentRoute: () => SidebarReviewCheckReviewCheckSyllabusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/review-check/syllabus': typeof SidebarReviewCheckReviewCheckSyllabusRouteWithChildren
  '/progress/': typeof SidebarProgressProgressIndexRoute
  '/review-check/': typeof SidebarReviewCheckReviewCheckIndexRoute
  '/review-check/syllabus/$syllabus_id/': typeof SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/review-check/syllabus': typeof SidebarReviewCheckReviewCheckSyllabusRouteWithChildren
  '/progress': typeof SidebarProgressProgressIndexRoute
  '/review-check': typeof SidebarReviewCheckReviewCheckIndexRoute
  '/review-check/syllabus/$syllabus_id': typeof SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_sidebar/_progress': typeof SidebarProgressRouteWithChildren
  '/_sidebar/_review-check': typeof SidebarReviewCheckRouteWithChildren
  '/book/write': typeof BookWriteRoute
  '/manage/delete': typeof ManageDeleteRoute
  '/manage/resume': typeof ManageResumeRoute
  '/manage/student': typeof ManageStudentRoute
  '/test/floating': typeof TestFloatingRoute
  '/book/': typeof BookIndexRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/_sidebar/_review-check/review-check/syllabus': typeof SidebarReviewCheckReviewCheckSyllabusRouteWithChildren
  '/_sidebar/_progress/progress/': typeof SidebarProgressProgressIndexRoute
  '/_sidebar/_review-check/review-check/': typeof SidebarReviewCheckReviewCheckIndexRoute
  '/_sidebar/_review-check/review-check/syllabus/$syllabus_id/': typeof SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/oauth/kakao/callback'
    | '/review-check/syllabus'
    | '/progress/'
    | '/review-check/'
    | '/review-check/syllabus/$syllabus_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book'
    | '/oauth/kakao/callback'
    | '/review-check/syllabus'
    | '/progress'
    | '/review-check'
    | '/review-check/syllabus/$syllabus_id'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/login'
    | '/profile'
    | '/_sidebar/_progress'
    | '/_sidebar/_review-check'
    | '/book/write'
    | '/manage/delete'
    | '/manage/resume'
    | '/manage/student'
    | '/test/floating'
    | '/book/'
    | '/oauth/kakao/callback'
    | '/_sidebar/_review-check/review-check/syllabus'
    | '/_sidebar/_progress/progress/'
    | '/_sidebar/_review-check/review-check/'
    | '/_sidebar/_review-check/review-check/syllabus/$syllabus_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  BookWriteRoute: typeof BookWriteRoute
  ManageDeleteRoute: typeof ManageDeleteRoute
  ManageResumeRoute: typeof ManageResumeRoute
  ManageStudentRoute: typeof ManageStudentRoute
  TestFloatingRoute: typeof TestFloatingRoute
  BookIndexRoute: typeof BookIndexRoute
  OauthKakaoCallbackRoute: typeof OauthKakaoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/floating': {
      id: '/test/floating'
      path: '/test/floating'
      fullPath: '/test/floating'
      preLoaderRoute: typeof TestFloatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/student': {
      id: '/manage/student'
      path: '/manage/student'
      fullPath: '/manage/student'
      preLoaderRoute: typeof ManageStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/resume': {
      id: '/manage/resume'
      path: '/manage/resume'
      fullPath: '/manage/resume'
      preLoaderRoute: typeof ManageResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/delete': {
      id: '/manage/delete'
      path: '/manage/delete'
      fullPath: '/manage/delete'
      preLoaderRoute: typeof ManageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/write': {
      id: '/book/write'
      path: '/book/write'
      fullPath: '/book/write'
      preLoaderRoute: typeof BookWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_review-check': {
      id: '/_sidebar/_review-check'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarReviewCheckRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/_progress': {
      id: '/_sidebar/_progress'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarProgressRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/oauth/kakao/callback': {
      id: '/oauth/kakao/callback'
      path: '/oauth/kakao/callback'
      fullPath: '/oauth/kakao/callback'
      preLoaderRoute: typeof OauthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/_review-check/review-check/': {
      id: '/_sidebar/_review-check/review-check/'
      path: '/review-check'
      fullPath: '/review-check/'
      preLoaderRoute: typeof SidebarReviewCheckReviewCheckIndexRouteImport
      parentRoute: typeof SidebarReviewCheckRoute
    }
    '/_sidebar/_progress/progress/': {
      id: '/_sidebar/_progress/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof SidebarProgressProgressIndexRouteImport
      parentRoute: typeof SidebarProgressRoute
    }
    '/_sidebar/_review-check/review-check/syllabus': {
      id: '/_sidebar/_review-check/review-check/syllabus'
      path: '/review-check/syllabus'
      fullPath: '/review-check/syllabus'
      preLoaderRoute: typeof SidebarReviewCheckReviewCheckSyllabusRouteImport
      parentRoute: typeof SidebarReviewCheckRoute
    }
    '/_sidebar/_review-check/review-check/syllabus/$syllabus_id/': {
      id: '/_sidebar/_review-check/review-check/syllabus/$syllabus_id/'
      path: '/$syllabus_id'
      fullPath: '/review-check/syllabus/$syllabus_id/'
      preLoaderRoute: typeof SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRouteImport
      parentRoute: typeof SidebarReviewCheckReviewCheckSyllabusRoute
    }
  }
}

interface SidebarProgressRouteChildren {
  SidebarProgressProgressIndexRoute: typeof SidebarProgressProgressIndexRoute
}

const SidebarProgressRouteChildren: SidebarProgressRouteChildren = {
  SidebarProgressProgressIndexRoute: SidebarProgressProgressIndexRoute,
}

const SidebarProgressRouteWithChildren = SidebarProgressRoute._addFileChildren(
  SidebarProgressRouteChildren,
)

interface SidebarReviewCheckReviewCheckSyllabusRouteChildren {
  SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute: typeof SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute
}

const SidebarReviewCheckReviewCheckSyllabusRouteChildren: SidebarReviewCheckReviewCheckSyllabusRouteChildren =
  {
    SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute:
      SidebarReviewCheckReviewCheckSyllabusSyllabus_idIndexRoute,
  }

const SidebarReviewCheckReviewCheckSyllabusRouteWithChildren =
  SidebarReviewCheckReviewCheckSyllabusRoute._addFileChildren(
    SidebarReviewCheckReviewCheckSyllabusRouteChildren,
  )

interface SidebarReviewCheckRouteChildren {
  SidebarReviewCheckReviewCheckSyllabusRoute: typeof SidebarReviewCheckReviewCheckSyllabusRouteWithChildren
  SidebarReviewCheckReviewCheckIndexRoute: typeof SidebarReviewCheckReviewCheckIndexRoute
}

const SidebarReviewCheckRouteChildren: SidebarReviewCheckRouteChildren = {
  SidebarReviewCheckReviewCheckSyllabusRoute:
    SidebarReviewCheckReviewCheckSyllabusRouteWithChildren,
  SidebarReviewCheckReviewCheckIndexRoute:
    SidebarReviewCheckReviewCheckIndexRoute,
}

const SidebarReviewCheckRouteWithChildren =
  SidebarReviewCheckRoute._addFileChildren(SidebarReviewCheckRouteChildren)

interface SidebarRouteChildren {
  SidebarProgressRoute: typeof SidebarProgressRouteWithChildren
  SidebarReviewCheckRoute: typeof SidebarReviewCheckRouteWithChildren
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarProgressRoute: SidebarProgressRouteWithChildren,
  SidebarReviewCheckRoute: SidebarReviewCheckRouteWithChildren,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  BookWriteRoute: BookWriteRoute,
  ManageDeleteRoute: ManageDeleteRoute,
  ManageResumeRoute: ManageResumeRoute,
  ManageStudentRoute: ManageStudentRoute,
  TestFloatingRoute: TestFloatingRoute,
  BookIndexRoute: BookIndexRoute,
  OauthKakaoCallbackRoute: OauthKakaoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
